### ISSUE TITLE
A question about 3.2 "PROMPT TUNING FOR SEMANTIC CORRESPONDENCE"

### ISSUE THREAD

**Issue by qiuqifeng2001** [ActiveVisionLab/SD4Match#1]
Thank you for your paper and the open-source code. It has been very helpful to me!

I have encountered some confusion while reading the code. When using `prompt_option=class`, I noticed that the `prompt_handler` (an implementation class of HiddenStateHandler) still retrieves an empty string ("") prompt when calling the `prompt_handler.get()` method, which is then passed to CLIP for encoding. I couldn't find prompts like `"a photo of {object class}"` as mentioned.

Could it be an issue with the parameters I passed? I am using the script file `script/spair/sd4match_class.sh` to launch it.

Looking forward to your reply. Thank you.

**Comment by Xinghui-Li** [comment]
Thank you for your interest in our work.

prompt_option=class corresponds to SD4Match-Class in the paper. It means that we **learn** one prompt for **each object category**. This prompt is purely learned and abstract and does not follow the template `a photo of a {object class}`. Since images belonging to the same category share the same prompt in this setting, the way that we implement it is using `prompt_handler.get()`, which takes in a list of image names and returns the corresponding learnable prompt. For example, if we input `[aeroplane_image1, areoplane_image2]`, it will return `[aeroplane_prompt, aeroplane_prompt]` because `aeroplane_image1` and `aeroplane_image2` will share the same prompt. It does not retrieve the empty string. If you refer to the empty string in Ln62 of `src/stable_diffusion/hidden_state.py`, this empty string is simply a way to initialize the learnable prompt. 

The prompt template `a photo of an {object class}` is employed by [DIFT](https://github.com/Tsingularity/dift). It is an inference-only method and does not require any training. We also integrate it to our pipeline. If you wish to test it, you can simply run `python test.py --config_file config/dift.py --prompt_type text --timestep 261`. This would retrieve the prompt template `a photo of a {category}.`

**Comment by qiuqifeng2001** [comment]
Thanks for your explanation, it has been very helpful for me!

**Comment by ThousandLayerCake** [comment]
Thanks for your explanation, it has been very helpful for me!
