### ISSUE TITLE
Question about testing time.

### ISSUE THREAD

**Issue by lyh200095** [ActiveVisionLab/SD4Match#2]
I use 3090ti for testing. With xformers and batch_size=4, it takes alomot 3 hours. What is the normal test time? Thank you!

**Comment by Xinghui-Li** [comment]
Thank you for your interest in our work. For SD4Match-Single and SD4Match-Class, it normally takes about 5mins. For SD4Match-CPM, as we cannot cache the feature map of each image in advance (because CPM module has to take each image pair individually), and SD itself is a very large model, it can take hours (about 1 sec per image pair).

**Comment by lyh200095** [comment]
Thank for you replying! It is very helpful to me.
